name: 'Deploy'

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Checkout version manifest
        uses: actions/checkout@v3
        with:
          path: versions
          repository: VRCFury/vrcfury-updater-manifest
          ssh-key: ${{ secrets.VERSION_DEPLOY_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd repo
          (cd .github/workflows && npm install)
          node .github/workflows/bundle.js
