name: 'Deploy'

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: repo
      - name: Checkout version manifest
        uses: actions/checkout@v3
        with:
          path: versions
          repository: VRCFury/vrcfury-updater-manifest
          ssh-key: ${{ secrets.VERSION_DEPLOY_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Bundle
        working-directory: repo
        run: |
          (cd .github/workflows && npm install)
          node .github/workflows/bundle.js
      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(date +%Y%m%d.%H%M%S)" >> $GITHUB_OUTPUT
      - name: Release Bundles
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: 'repo/dist/*'
      - name: Update deployment URLs
        working-directory: repo
        run: node .github/workflows/updateUrls.js
        env:
          RELEASE_ASSETS: ${{ steps.release.outputs.assets }}
      - name: Push version manifest
        working-directory: versions
        run: |
          git diff
          git config user.name VRCFury Releases
          git config user.email noreply@vrcfury.com
          git add .
          git commit -m "Release from $GITHUB_SHA"
          git push
