name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: .github/workflows/test_project
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.31f1
        vrcsdkVersion:
          - 2022
          - 3.0.9
          - 3.3.0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: $PROJECT_PATH/Library
          key: Library-${{ matrix.image }}-${{ matrix.vrcsdkVersion }}
          restore-keys: |
            Library-${{ matrix.image }}
            Library-

      - name: Download VRCSDK
        run: |
          if [[ "${{ matrix.vrcsdkVersion }}" == "2022" ]]; then
            curl -L -o "vrcsdk.zip" "https://github.com/VRCFury/VRCFury/releases/download/old-vrcsdk/VRCSDK.zip"
            unzip "vrcsdk.zip" -d "$PROJECT_PATH/Assets"
          elif [[ "${{ matrix.vrcsdkVersion }}" == "3.0.9" ]]; then
            curl -L -o "avatars.zip" "https://github.com/vrchat/packages/releases/download/3.1.9/com.vrchat.avatars-3.0.9.zip"
            curl -L -o "base.zip" "https://github.com/vrchat/packages/releases/download/3.1.9/com.vrchat.base-3.0.9.zip"
            mkdir -p "$PROJECT_PATH/Packages/com.vrchat.avatars"
            mkdir -p "$PROJECT_PATH/Packages/com.vrchat.base"
            unzip avatars.zip -d "$PROJECT_PATH/Packages/com.vrchat.avatars"
            unzip base.zip -d "$PROJECT_PATH/Packages/com.vrchat.base"
          elif [[ "${{ matrix.vrcsdkVersion }}" == "3.3.0" ]]; then
            curl -L -o "avatars.zip" "https://github.com/vrchat/packages/releases/download/3.3.0/com.vrchat.avatars-3.3.0.zip"
            curl -L -o "base.zip" "https://github.com/vrchat/packages/releases/download/3.3.0/com.vrchat.base-3.3.0.zip"
            mkdir -p "$PROJECT_PATH/Packages/com.vrchat.avatars"
            mkdir -p "$PROJECT_PATH/Packages/com.vrchat.base"
            unzip avatars.zip -d "$PROJECT_PATH/Packages/com.vrchat.avatars"
            unzip base.zip -d "$PROJECT_PATH/Packages/com.vrchat.base"
          else
            echo "What"
            exit 1
          fi

      - name: Unity Test
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ env.PROJECT_PATH }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
